#!/bin/bash -f
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -t 72:00:00
#SBATCH --mem 6GB
#SBATCH -p gpu
#SBATCH --gres=gpu:1
#SBATCH --export=ALL
#SBATCH -o amber-%j.o
#SBATCH -e amber-%j.err

# replace STARTDIR with your current directory:
cd /scratch/ejd119/

${AMBERHOME}/bin/pmemd.cuda -O -i eq3.in -o ygap_eq3.out -p ygap_sol.prmtop -c ygap_heat2_mmp.ncrst -r ygap_eq3.ncrst -x ygap_eq3.nc -inf ygap_eq3.mdinfo

# comments here`
